name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Change Directories To Server
      run: cd YamhilliaNET
    - name: Install dependencies
      run: dotnet restore YamhilliaNET
    - name: Build
      run: dotnet build YamhilliaNET --configuration Release --no-restore
    - name: Install Test dependencies
      run: dotnet restore YamhilliaNETTests
    - name: Build Tests
      run: dotnet build YamhilliaNETTests --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
